#ifndef _MODEL_WORK_WITH_TARGETS_ON_UI_H
#define _MODEL_WORK_WITH_TARGETS_ON_UI_H


ALL_LABEL_INFORMATION HandlePressedLabel (QString , ALL_LABEL_INFORMATION );
ALL_LABEL_INFORMATION HandlePressedButton (QString , ALL_LABEL_INFORMATION );

#endif // _MODEL_WORK_WITH_TARGETS_ON_UI_H
